services:
  mariadb:
    image: bitnamilegacy/mariadb:12.0.2
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=moodlelocal
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_ROOT_PASSWORD=moodlelocal
      - MARIADB_EXTRA_FLAGS=--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnamilegacy/moodle:5.0.2
    depends_on:
      - mariadb
    ports:
      - "8888:8080"
      - "8443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=moodlelocal
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=moodlelocal
      - MOODLE_EMAIL=tutor@ubu.es
      - MOODLE_SITE_NAME=Moodle Local UBUMonitor
    volumes:
      - moodle_data:/bitnami/moodle
      - ./certs/tls.crt:/opt/bitnami/apache/conf/bitnami/certs/tls.crt:ro
      - ./certs/tls.key:/opt/bitnami/apache/conf/bitnami/certs/tls.key:ro
      - ./php_personalizado.ini:/opt/bitnami/php/etc/conf.d/personalizado.ini:ro

volumes:
  mariadb_data:
  moodle_data:
